### ISSUE TITLE
Version 0.9.8

### ISSUE THREAD

**Issue by jonashrem** [CMoH/gnome15-overlay#25]
Hi,

Version 0.9.8 is out (see https://projects.russo79.com/attachments/download/153/gnome15-0.9.8.tar.gz ) 

Hope that doesn't annoy you. just in case you didn't see ;)

**Comment by CMoH** [comment]
Sorry, the website is down. The sources I had in my local git do not have a 0.9.8 tag, so there's not much to do until the russo79.com is back up.

**Comment by jonashrem** [comment]
Yeah, I think it's down for 3 month nows. I don't expect too much of ever coming back. 

Someone cloned it at gizthub https://github.com/makei/gnome15 but not sure if this was somehow patched and doens't seem to be tag version anyways. Also here are some sources hich seem up to date but couln't find a download all button on first glance.

As 0.9.7 runs fine anyway and 0.9.8 brings nothing realy important But sad that it got abondened. I realy like my keyboard ;) .

**Comment by CMoH** [comment]
I contacted the webmaster of russo79.com. He replied that he intends to continue work and fix the website. Let's hope this will actually happen.

In the meantime I have uploaded my local git clone to github, although I still need some dependencies (see #26 for a list)

I think this issue is worth reopening when he does that. I'll close it for now, and keep monitoring :)

**Comment by evadim** [comment]
Hi there!

Seems, overlay online :)
I have copypaste ebuild for this version, so - I have sources on my local drive, if anybody need them.

**Comment by jonashrem** [comment]
Hi, what do you mean with overlay online? You mean this overlay? 

If you have the libg15-gnome15-1.3.0.3.tar.gz  in /usr/portage/distfiles please upload somewhere and put in #27

**Comment by evadim** [comment]
@jonashrem yes, I mean this one. Sorry for noise, I look into another tasks and see what everything what I have alredy found.
