### ISSUE TITLE
glome15 with gstreamer flag fails to configure

### ISSUE THREAD

**Issue by Delicates** [CMoH/gnome15-overlay#26]
If I try to build app-misc/gnome15-0.9.7-r3::gnome15 with gstreamer flag, it fails during config:

    ...
    checking python2.7 module: sensors... yes
    checking for initLibG15 in -lg15... no
    checking for FFTW... yes
    checking for PULSE... no
    configure: error: Plugin Mediaplayer cannot be built without gst python module

This is despite having dev-python/gst-python-1.2.1 installed.

Check this whenever you do v0.9.8 ebuild.
Perhaps there's some dependency missing?

**Comment by CMoH** [comment]
I don't know if you noticed, but www.russo79.com/gnome15 is down. This makes the gnome15 source tars unavailable for download using the regular ebuilds. I have cleaned my distfiles, and some of the dependencies are missing.

Can you provide these files for me, so I can continue maintaining the overlay? I can store them on my webserver temporarily, until russo79 is back online (I have contacted the webmaster and he intends to repair the project website)

Here is a list of files I am missing:

* libg15-gnome15-1.3.0.3.tar.gz
* pyinputevent-0.1c.tar.gz
* cairoplot-gnome15-1.1b.tar.gz
* PySensors-0.0.2.tar.gz
* pylibg19-0.0.7.tar.gz

I still had the gnome15 sources in my local git clone, which I uploaded to https://github.com/CMoH/gnome15, so those are not necessary.

I hope you can provide these files for me, so I can start working on the actual problem you reported.

**Comment by CMoH** [comment]
Actually, the tar.bz2 files of gnome15-0.9.6 and 0.9.7 would also be useful. Can you please pass them over too?

Explanation: github recompresses the sources from scratch, which changes the checksum of the tar.bz2 files, which makes portage complain unless everybody removes the old tar.bz2 from the local cache.

Thanks!

**Comment by jonashrem** [comment]
I'm not Delicates but maybe you can use mine as well for the start. 

http://codeinbarrels.net/jonas/gnome15.deps.tar.xz

I'm afraid it is missing libg15-gnome as I own the g19. Hope Delicates or someone still has that one.

I also found those in my downloads folder not sure the origin but could be the origiinal

http://codeinbarrels.net/jonas/gnome15-0.9.8.tar.gz

**Comment by jonashrem** [comment]
p.s. I am not sure it is the reason and I don't want to make tests at the moment but I have both slots of   dev-python/gst-python installed  ( (0.10) 0.10.22-r1 and  (1.0)  1.2.1)

Maybe that helps you @Delicates

**Comment by CMoH** [comment]
@jonashrem thanks - new ebuilds point towards valid sources. Opened #27 to continue this

**Comment by Delicates** [comment]
Thanks for fixing the ebuild.
Unfortunately, being G19 user, I also don't have libg15-gnome15-1.3.0.3.tar.gz
