### ISSUE TITLE
gnome15: switch dep from virtual/python-imaging to dev-python/pillow

### ISSUE THREAD

**Issue by evadim** [CMoH/gnome15-overlay#32]
during update, portage show warning:

The following mask changes are necessary to proceed:
 (see "package.unmask" in the portage(5) man page for more details)
 required by app-misc/gnome15-0.10.2::gnome15
 required by @selected
 required by @world (argument)
 /usr/portage/profiles/package.mask:
 Justin Lecher (10 Nov 2015)
 Compatibility virtual for transition from
 dev-python/imaging to dev-python/pillow
 obsolete now #508266
=virtual/python-imaging-2

**Comment by CMoH** [comment]
Thanks - fixed in dd6628376d5d8af495f216ede5748c2b8c952316
